# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_HEADLOCATIONS = descriptor.EnumDescriptor(
  name='HeadLocations',
  full_name='HeadLocations',
  filename='HeadLocations',
  values=[
    descriptor.EnumValueDescriptor(
      name='NZ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FP1', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FPZ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FP2', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AF7', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AF3', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AFZ', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AF4', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AF8', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F9', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F7', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F5', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F3', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F1', index=13, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FZ', index=14, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F2', index=15, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F4', index=16, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F6', index=17, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F8', index=18, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='F10', index=19, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FT9', index=20, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FT7', index=21, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FC5', index=22, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FC3', index=23, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FC1', index=24, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FCZ', index=25, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FC2', index=26, number=27,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FC4', index=27, number=28,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FC6', index=28, number=29,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FT8', index=29, number=30,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FT10', index=30, number=31,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='A1', index=31, number=32,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='T9', index=32, number=33,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='T7', index=33, number=34,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='C5', index=34, number=35,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='C3', index=35, number=36,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='C1', index=36, number=37,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CZ', index=37, number=38,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='C2', index=38, number=39,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='C4', index=39, number=40,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='C6', index=40, number=41,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='T8', index=41, number=42,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='T10', index=42, number=43,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='A2', index=43, number=44,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TP9', index=44, number=45,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TP7', index=45, number=46,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CP5', index=46, number=47,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CP3', index=47, number=48,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CP1', index=48, number=49,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CPZ', index=49, number=50,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CP2', index=50, number=51,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CP4', index=51, number=52,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CP6', index=52, number=53,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TP8', index=53, number=54,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TP10', index=54, number=55,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P9', index=55, number=56,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P7', index=56, number=57,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P5', index=57, number=58,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P3', index=58, number=59,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P1', index=59, number=60,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PZ', index=60, number=61,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P2', index=61, number=62,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P4', index=62, number=63,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P6', index=63, number=64,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P8', index=64, number=65,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='P10', index=65, number=66,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PO7', index=66, number=67,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PO3', index=67, number=68,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POZ', index=68, number=69,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PO4', index=69, number=70,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PO8', index=70, number=71,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='O1', index=71, number=72,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OZ', index=72, number=73,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='O2', index=73, number=74,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IZ', index=74, number=75,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AUX1', index=75, number=76,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AUX2', index=76, number=77,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AUX3', index=77, number=78,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AUX4', index=78, number=79,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MUSE_LEFT_AUX', index=79, number=80,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MUSE_RIGHT_AUX', index=80, number=81,
      options=None,
      type=None),
  ],
  options=None,
)


_EEGUNITS = descriptor.EnumDescriptor(
  name='EEGUnits',
  full_name='EEGUnits',
  filename='EEGUnits',
  values=[
    descriptor.EnumValueDescriptor(
      name='EEG_MICROVOLTS', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EEG_MUSE1_RAW', index=1, number=2,
      options=None,
      type=None),
  ],
  options=None,
)

_ACCELEROMETERUNITS = descriptor.EnumDescriptor(
  name='AccelerometerUnits',
  full_name='AccelerometerUnits',
  filename='AccelerometerUnits',
  values=[
    descriptor.EnumValueDescriptor(
      name='ACC_GFORCE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACC_MUSE1_RAW', index=1, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


NZ = 1
FP1 = 2
FPZ = 3
FP2 = 4
AF7 = 5
AF3 = 6
AFZ = 7
AF4 = 8
AF8 = 9
F9 = 10
F7 = 11
F5 = 12
F3 = 13
F1 = 14
FZ = 15
F2 = 16
F4 = 17
F6 = 18
F8 = 19
F10 = 20
FT9 = 21
FT7 = 22
FC5 = 23
FC3 = 24
FC1 = 25
FCZ = 26
FC2 = 27
FC4 = 28
FC6 = 29
FT8 = 30
FT10 = 31
A1 = 32
T9 = 33
T7 = 34
C5 = 35
C3 = 36
C1 = 37
CZ = 38
C2 = 39
C4 = 40
C6 = 41
T8 = 42
T10 = 43
A2 = 44
TP9 = 45
TP7 = 46
CP5 = 47
CP3 = 48
CP1 = 49
CPZ = 50
CP2 = 51
CP4 = 52
CP6 = 53
TP8 = 54
TP10 = 55
P9 = 56
P7 = 57
P5 = 58
P3 = 59
P1 = 60
PZ = 61
P2 = 62
P4 = 63
P6 = 64
P8 = 65
P10 = 66
PO7 = 67
PO3 = 68
POZ = 69
PO4 = 70
PO8 = 71
O1 = 72
OZ = 73
O2 = 74
IZ = 75
AUX1 = 76
AUX2 = 77
AUX3 = 78
AUX4 = 79
MUSE_LEFT_AUX = 80
MUSE_RIGHT_AUX = 81
EEG_MICROVOLTS = 1
EEG_MUSE1_RAW = 2
ACC_GFORCE = 1
ACC_MUSE1_RAW = 2


_MUSEDATA_DATATYPE = descriptor.EnumDescriptor(
  name='Datatype',
  full_name='MuseData.Datatype',
  filename='Datatype',
  values=[
    descriptor.EnumValueDescriptor(
      name='EEG', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='QUANT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACCEL', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BATTERY', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VERSION', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONFIG', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ANNOTATION', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HISTOGRAM', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ALGVALUE', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DSP', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COMPUTING_DEVICE', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EEG_DROPPED', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACC_DROPPED', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CALM_APP', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CALM_ALG', index=14, number=14,
      options=None,
      type=None),
  ],
  options=None,
)

_ANNOTATION_FORMAT = descriptor.EnumDescriptor(
  name='Format',
  full_name='Annotation.Format',
  filename='Format',
  values=[
    descriptor.EnumValueDescriptor(
      name='PLAIN_STRING', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JSON', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OSC', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_MUSEDATACOLLECTION = descriptor.Descriptor(
  name='MuseDataCollection',
  full_name='MuseDataCollection',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='collection', full_name='MuseDataCollection.collection', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MUSEDATA = descriptor.Descriptor(
  name='MuseData',
  full_name='MuseData',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='MuseData.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datatype', full_name='MuseData.datatype', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='config_id', full_name='MuseData.config_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MUSEDATA_DATATYPE,
  ],
  options=None)


_EEG = descriptor.Descriptor(
  name='EEG',
  full_name='EEG',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='EEG.values', index=0,
      number=2, type=2, cpp_type=6, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='drl', full_name='EEG.drl', index=1,
      number=5, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ref', full_name='EEG.ref', index=2,
      number=6, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='EEG.museData', index=0,
      number=8, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MUSEQUANTIZATION = descriptor.Descriptor(
  name='MuseQuantization',
  full_name='MuseQuantization',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='MuseQuantization.values', index=0,
      number=1, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='MuseQuantization.museData', index=0,
      number=9, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACCELEROMETER = descriptor.Descriptor(
  name='Accelerometer',
  full_name='Accelerometer',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='acc1', full_name='Accelerometer.acc1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='acc2', full_name='Accelerometer.acc2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='acc3', full_name='Accelerometer.acc3', index=2,
      number=3, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='Accelerometer.museData', index=0,
      number=10, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ANNOTATION = descriptor.Descriptor(
  name='Annotation',
  full_name='Annotation',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='event_data', full_name='Annotation.event_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_data_format', full_name='Annotation.event_data_format', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_type', full_name='Annotation.event_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_id', full_name='Annotation.event_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parent_id', full_name='Annotation.parent_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='Annotation.museData', index=0,
      number=100, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _ANNOTATION_FORMAT,
  ],
  options=None)


_BATTERY = descriptor.Descriptor(
  name='Battery',
  full_name='Battery',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='percent_remaining', full_name='Battery.percent_remaining', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battery_fuel_gauge_millivolts', full_name='Battery.battery_fuel_gauge_millivolts', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battery_adc_millivolts', full_name='Battery.battery_adc_millivolts', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temperature_celsius', full_name='Battery.temperature_celsius', index=3,
      number=4, type=17, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='Battery.museData', index=0,
      number=101, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MUSEVERSION = descriptor.Descriptor(
  name='MuseVersion',
  full_name='MuseVersion',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hardware_version', full_name='MuseVersion.hardware_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='firmware_headset_version', full_name='MuseVersion.firmware_headset_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='firmware_type', full_name='MuseVersion.firmware_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='firmware_bootloader_version', full_name='MuseVersion.firmware_bootloader_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='build_number', full_name='MuseVersion.build_number', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='protocol_version', full_name='MuseVersion.protocol_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='MuseVersion.museData', index=0,
      number=102, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MUSECONFIG = descriptor.Descriptor(
  name='MuseConfig',
  full_name='MuseConfig',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mac_addr', full_name='MuseConfig.mac_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serial_number', full_name='MuseConfig.serial_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='preset', full_name='MuseConfig.preset', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='compression_enabled', full_name='MuseConfig.compression_enabled', index=3,
      number=100, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filters_enabled', full_name='MuseConfig.filters_enabled', index=4,
      number=201, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='notch_frequency_hz', full_name='MuseConfig.notch_frequency_hz', index=5,
      number=202, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_sample_frequency_hz', full_name='MuseConfig.eeg_sample_frequency_hz', index=6,
      number=203, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_output_frequency_hz', full_name='MuseConfig.eeg_output_frequency_hz', index=7,
      number=204, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_samples_bitwidth', full_name='MuseConfig.eeg_samples_bitwidth', index=8,
      number=205, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_channel_count', full_name='MuseConfig.eeg_channel_count', index=9,
      number=206, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_channel_layout', full_name='MuseConfig.eeg_channel_layout', index=10,
      number=207, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_downsample', full_name='MuseConfig.eeg_downsample', index=11,
      number=208, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_units', full_name='MuseConfig.eeg_units', index=12,
      number=209, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_locations', full_name='MuseConfig.eeg_locations', index=13,
      number=210, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eeg_conversion_factor', full_name='MuseConfig.eeg_conversion_factor', index=14,
      number=211, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='afe_gain', full_name='MuseConfig.afe_gain', index=15,
      number=212, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='drlref_data_enabled', full_name='MuseConfig.drlref_data_enabled', index=16,
      number=300, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='drlref_conversion_factor', full_name='MuseConfig.drlref_conversion_factor', index=17,
      number=301, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='drlref_sample_frequency_hz', full_name='MuseConfig.drlref_sample_frequency_hz', index=18,
      number=302, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='acc_data_enabled', full_name='MuseConfig.acc_data_enabled', index=19,
      number=400, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='acc_units', full_name='MuseConfig.acc_units', index=20,
      number=401, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='acc_conversion_factor', full_name='MuseConfig.acc_conversion_factor', index=21,
      number=402, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='acc_sample_frequency_hz', full_name='MuseConfig.acc_sample_frequency_hz', index=22,
      number=403, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battery_data_enabled', full_name='MuseConfig.battery_data_enabled', index=23,
      number=500, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battery_percent_remaining', full_name='MuseConfig.battery_percent_remaining', index=24,
      number=501, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battery_millivolts', full_name='MuseConfig.battery_millivolts', index=25,
      number=502, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_data_enabled', full_name='MuseConfig.error_data_enabled', index=26,
      number=600, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='MuseConfig.museData', index=0,
      number=103, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_EEG_DROPPEDSAMPLES = descriptor.Descriptor(
  name='EEG_DroppedSamples',
  full_name='EEG_DroppedSamples',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='num', full_name='EEG_DroppedSamples.num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='EEG_DroppedSamples.museData', index=0,
      number=202, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACC_DROPPEDSAMPLES = descriptor.Descriptor(
  name='ACC_DroppedSamples',
  full_name='ACC_DroppedSamples',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='num', full_name='ACC_DroppedSamples.num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='ACC_DroppedSamples.museData', index=0,
      number=203, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_COMPUTINGDEVICE = descriptor.Descriptor(
  name='ComputingDevice',
  full_name='ComputingDevice',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='os_type', full_name='ComputingDevice.os_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='os_version', full_name='ComputingDevice.os_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hardware_model_name', full_name='ComputingDevice.hardware_model_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hardware_model_id', full_name='ComputingDevice.hardware_model_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processor_name', full_name='ComputingDevice.processor_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='processor_speed', full_name='ComputingDevice.processor_speed', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='number_of_processors', full_name='ComputingDevice.number_of_processors', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='memory_size', full_name='ComputingDevice.memory_size', index=7,
      number=8, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bluetooth_version', full_name='ComputingDevice.bluetooth_version', index=8,
      number=9, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_zone', full_name='ComputingDevice.time_zone', index=9,
      number=10, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_zone_offset_seconds', full_name='ComputingDevice.time_zone_offset_seconds', index=10,
      number=11, type=17, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='ComputingDevice.museData', index=0,
      number=201, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DSP = descriptor.Descriptor(
  name='DSP',
  full_name='DSP',
  filename='Muse_v2.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='DSP.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='float_array', full_name='DSP.float_array', index=1,
      number=2, type=2, cpp_type=6, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int_array', full_name='DSP.int_array', index=2,
      number=3, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='DSP.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='museData', full_name='DSP.museData', index=0,
      number=200, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MUSEDATACOLLECTION.fields_by_name['collection'].message_type = _MUSEDATA
_MUSEDATA.fields_by_name['datatype'].enum_type = _MUSEDATA_DATATYPE
_ANNOTATION.fields_by_name['event_data_format'].enum_type = _ANNOTATION_FORMAT
_MUSECONFIG.fields_by_name['eeg_units'].enum_type = _EEGUNITS
_MUSECONFIG.fields_by_name['eeg_locations'].enum_type = _HEADLOCATIONS
_MUSECONFIG.fields_by_name['acc_units'].enum_type = _ACCELEROMETERUNITS

class MuseDataCollection(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MUSEDATACOLLECTION

class MuseData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MUSEDATA

class EEG(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EEG

class MuseQuantization(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MUSEQUANTIZATION

class Accelerometer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCELEROMETER

class Annotation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANNOTATION

class Battery(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTERY

class MuseVersion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MUSEVERSION

class MuseConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MUSECONFIG

class EEG_DroppedSamples(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EEG_DROPPEDSAMPLES

class ACC_DroppedSamples(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACC_DROPPEDSAMPLES

class ComputingDevice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMPUTINGDEVICE

class DSP(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DSP

_EEG.extensions_by_name['museData'].message_type = _EEG
MuseData.RegisterExtension(_EEG.extensions_by_name['museData'])
_MUSEQUANTIZATION.extensions_by_name['museData'].message_type = _MUSEQUANTIZATION
MuseData.RegisterExtension(_MUSEQUANTIZATION.extensions_by_name['museData'])
_ACCELEROMETER.extensions_by_name['museData'].message_type = _ACCELEROMETER
MuseData.RegisterExtension(_ACCELEROMETER.extensions_by_name['museData'])
_ANNOTATION.extensions_by_name['museData'].message_type = _ANNOTATION
MuseData.RegisterExtension(_ANNOTATION.extensions_by_name['museData'])
_BATTERY.extensions_by_name['museData'].message_type = _BATTERY
MuseData.RegisterExtension(_BATTERY.extensions_by_name['museData'])
_MUSEVERSION.extensions_by_name['museData'].message_type = _MUSEVERSION
MuseData.RegisterExtension(_MUSEVERSION.extensions_by_name['museData'])
_MUSECONFIG.extensions_by_name['museData'].message_type = _MUSECONFIG
MuseData.RegisterExtension(_MUSECONFIG.extensions_by_name['museData'])
_EEG_DROPPEDSAMPLES.extensions_by_name['museData'].message_type = _EEG_DROPPEDSAMPLES
MuseData.RegisterExtension(_EEG_DROPPEDSAMPLES.extensions_by_name['museData'])
_ACC_DROPPEDSAMPLES.extensions_by_name['museData'].message_type = _EEG_DROPPEDSAMPLES
MuseData.RegisterExtension(_ACC_DROPPEDSAMPLES.extensions_by_name['museData'])
_COMPUTINGDEVICE.extensions_by_name['museData'].message_type = _COMPUTINGDEVICE
MuseData.RegisterExtension(_COMPUTINGDEVICE.extensions_by_name['museData'])
_DSP.extensions_by_name['museData'].message_type = _DSP
MuseData.RegisterExtension(_DSP.extensions_by_name['museData'])
